# Azure Database for MySQL deployment
# Run your scripts and make changes to your Azure Database for MySQL
 # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: mysql
    displayName: mysql
    pool:
      vmImage: $(vmImageName)

    steps:
- task: AzureMysqlDeployment@1
  inputs:
    ConnectedServiceName: lab-projects-sp
    ServerName:shinelab.mysql.database.azure.com
    #DatabaseName: # Optional
    SqlUsername:shinelab
    SqlPassword:admin123$
    #TaskNameSelector: 'SqlTaskFile' # Optional. Options: SqlTaskFile, InlineSqlTask
    #SqlFile: # Required when taskNameSelector == SqlTaskFile
    #SqlInline: # Required when taskNameSelector == InlineSqlTask
    #SqlAdditionalArguments: # Optional
    #IpDetectionMethod: 'AutoDetect' # Options: AutoDetect, IPAddressRange
    #StartIpAddress: # Required when ipDetectionMethod == IPAddressRange
    #EndIpAddress: # Required when ipDetectionMethod == IPAddressRange
    #DeleteFirewallRule: true # Optional